# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.
name: demoapp-CI

trigger:
- none

# Trigger the workflow on push to the master branch, and only for changes to lu or json files
on:
  push:
    branches:
      - master
    paths:
      - 'luis-app/*.lu'
      - 'luis-app/tests/*.json'
      
env:
  AZURE_WEBAPP_NAME: demoapp   # set this to your application's name
  NODE_VERSION: '14.x' # set this to the node version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@main
   
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Setup Node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: 'npm install, build, and test'
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
      working-directory:  my-app-path
               
    # deploy web app using Azure credentials
    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    # Azure logout 
    - name: logout
      run: |
        az logout
